CREATE OR REPLACE PROCEDURE proc
(
    IN CITY_ID INT,
    OUT CITY_NAME VARCHAR(30)
)
P1: BEGIN
    SELECT NAME
    INTO CITY_NAME
    FROM CITIES c
    WHERE c.CITYID = CITY_ID;
END P1@


--CALL proc('1',res)@
--VALUES res@