CREATE OR REPLACE FUNCTION funkcja
(
    IN CUSTOMER_ID INT
)
RETURNS VARCHAR(50)
LANGUAGE SQL
BEGIN
    DECLARE FULLNAME VARCHAR(50);
    SELECT LASTNAME || ', ' || FIRSTNAME
    INTO FULLNAME
    FROM CUSTOMERS
    WHERE CUSTOMERID = CUSTOMER_ID;

    RETURN FULLNAME;
END@

--SELECT funkcja(1) FROM SYSIBM.SYSDUMMY1@