CREATE OR REPLACE TRIGGER trigger
BEFORE INSERT ON CUSTOMERS
REFERENCING NEW AS new_row
FOR EACH ROW
BEGIN ATOMIC
    IF new_row.SALARY > 50000 THEN
        SET new_row.HIREDATE = CURRENT_DATE;
    END IF;
END@